[project]
name = "pandora"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "angr>=9.2.199",
    "ansi2html>=1.9.2",
    "claripy>=9.2.183",
    "cle>=9.2.183",
    "dominate>=2.9.1",
    "ipython>=9.7.0",
    "json5>=0.12.1",
    "pre-commit>=4.5.1",
    "pyvex>=9.2.183",
    "typer>=0.20.0",
    "unicorn>=2.1.4",
]
