name: Sancus validation
on: [push, pull_request]

jobs:
  matrix-gen:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{steps.list_dirs.outputs.matrix}}
    steps:
      - uses: actions/checkout@v5
        with:
          repository: pandora-tee/pandora-examples
          sparse-checkout: |
            sancus/
      - id: list_dirs
        run: |
          cd sancus/
          MATRIX=$(find -mindepth 2 -type d | jq -cnR '[inputs | select(length>0)]')
          echo $MATRIX
          echo "::set-output name=matrix::$MATRIX"

  test:
    runs-on: ubuntu-22.04
    needs: matrix-gen
    strategy:
      fail-fast: false
      matrix:
        testcase: ${{fromJson(needs.matrix-gen.outputs.matrix)}}

    steps:
      - name: Check out repository
        uses: actions/checkout@v5
      - name: Install pandora/angr dependencies
        run: |
          sudo apt-get install python3 python3-pip python3-venv -y
          git clone https://github.com/pandora-tee/pandora && cd pandora
          git clone https://github.com/angr/angr-platforms
          python3 -m venv .venv && . .venv/bin/activate && python3 -m pip install -r requirements.txt && cd angr-platforms && python3 -m pip install .
      - name: Symbolic validation of ${{ matrix.testcase }}
        run: |
          cd ${{ github.workspace }}/pandora/
          source .venv/bin/activate
          ./pandora.py run -n 30 -p ptr,cf -c config-ci.ini --pandora-option PANDORA_EXPLORE_STACK_DEPTH=1500 ${{ github.workspace }}/sancus/${{ matrix.testcase }}/main.elf
